# Autogenerated wrapper script for PRIMA_jll for x86_64-apple-darwin-libgfortran5
export libprimac, libprimaf

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("PRIMA")
JLLWrappers.@declare_library_product(libprimac, "@rpath/libprimac.dylib")
JLLWrappers.@declare_library_product(libprimaf, "@rpath/libprimaf.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libprimac,
        "lib/libprimac.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libprimaf,
        "lib/libprimaf.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
